// Generated by gencpp from file football_game/ReachGoal.msg
// DO NOT EDIT!


#ifndef FOOTBALL_GAME_MESSAGE_REACHGOAL_H
#define FOOTBALL_GAME_MESSAGE_REACHGOAL_H

#include <ros/service_traits.h>


#include <football_game/ReachGoalRequest.h>
#include <football_game/ReachGoalResponse.h>


namespace football_game
{

struct ReachGoal
{

typedef ReachGoalRequest Request;
typedef ReachGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReachGoal
} // namespace football_game


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::football_game::ReachGoal > {
  static const char* value()
  {
    return "959d8712aaa1507c9a1417b801028273";
  }

  static const char* value(const ::football_game::ReachGoal&) { return value(); }
};

template<>
struct DataType< ::football_game::ReachGoal > {
  static const char* value()
  {
    return "football_game/ReachGoal";
  }

  static const char* value(const ::football_game::ReachGoal&) { return value(); }
};


// service_traits::MD5Sum< ::football_game::ReachGoalRequest> should match 
// service_traits::MD5Sum< ::football_game::ReachGoal > 
template<>
struct MD5Sum< ::football_game::ReachGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::football_game::ReachGoal >::value();
  }
  static const char* value(const ::football_game::ReachGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::football_game::ReachGoalRequest> should match 
// service_traits::DataType< ::football_game::ReachGoal > 
template<>
struct DataType< ::football_game::ReachGoalRequest>
{
  static const char* value()
  {
    return DataType< ::football_game::ReachGoal >::value();
  }
  static const char* value(const ::football_game::ReachGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::football_game::ReachGoalResponse> should match 
// service_traits::MD5Sum< ::football_game::ReachGoal > 
template<>
struct MD5Sum< ::football_game::ReachGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::football_game::ReachGoal >::value();
  }
  static const char* value(const ::football_game::ReachGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::football_game::ReachGoalResponse> should match 
// service_traits::DataType< ::football_game::ReachGoal > 
template<>
struct DataType< ::football_game::ReachGoalResponse>
{
  static const char* value()
  {
    return DataType< ::football_game::ReachGoal >::value();
  }
  static const char* value(const ::football_game::ReachGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOOTBALL_GAME_MESSAGE_REACHGOAL_H
